import tequila as tq
import numpy as np
import os
import shutil
import json
from pathlib import Path
import logging
import subprocess as sp
import pyscf
from pyscf import fci
import OrbOpt_helper


'''
Definitions/Parameters
'''                       
iteration_energies = [] #Stores the energies at the beginning of each iteration step after the VQE
all_occ_number = [] #Stores the orbital occupations at the beginning of each iteration step after the VQE
iterations = 6
molecule_name = "c6h6"
box_size = 50.0
wavelet_order = 7 #Default parameter of Orbital-generation, do not change without changing in Orbital-generation!!!
madness_thresh = 0.0001
optimization_thresh = 0.001
NO_occupation_thresh = 0.001


geometry_angstrom = """
C 0.000000 1.396792 0.000000
C 0.000000 -1.396792 0.000000
C 1.209657 0.698396 0.000000
C -1.209657 -0.698396 0.000000
C -1.209657 0.698396 0.000000
C 1.209657 -0.698396 0.000000
H 0.000000 2.484212 0.000000
H 2.151390 1.242106 0.000000
H -2.151390 -1.242106 0.000000
H -2.151390 1.242106 0.000000
H 2.151390 -1.242106 0.000000
H 0.000000 -2.484212 0.000000
"""

geometry_bohr = OrbOpt_helper.convert_geometry_from_angstrom_to_bohr(geometry_angstrom)


OrbOpt_helper.create_molecule_file(geometry_bohr) #Important here geometry in Bohr
mol = tq.Molecule(geometry_angstrom, dft={"L":box_size}, name=molecule_name) #Important here geometry in Angstrom

number_total_orbs = 36 # Number of orbitals generated by tequila. This number must be kept, otherwise n_pno=“read” will not work -> Alternatively adjust pnoinfo
all_orbitals = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,33,34,35] # All orbitals that are relevant (other orbitals are neither optimized nor included in multi-particle WF)
frozen_occupied_orbitals = [0,1,2,3,4,5,6,7,9,11,13,14,15,16,17,18,19,20] # HF orbitals that remain frozen (are not optimized) and are double occupied
active_orbitals = [8,10,12,33,34,35] # Active HF orbitals and PNOs



# Copy initial orbitals and intergals to folder for first step
os.mkdir("0")
for orb in all_orbitals:
    shutil.move("mra_orbital_" + str(orb) + ".00000", "0/mra_orbital_" + str(orb) + ".00000")
shutil.move(molecule_name + "_htensor.npy", "0/htensor.npy")
shutil.move(molecule_name + "_gtensor.npy", "0/gtensor.npy")


'''
Iteration Loop
'''
for it in range(iterations):
    it_str = it.__str__()
    print("Iteration-Step: " + it_str)
    # Copy h and g tensors for VQE to current folder to read molecule
    shutil.copy(it_str + "/htensor.npy", molecule_name + "_htensor.npy")
    shutil.copy(it_str + "/gtensor.npy", molecule_name + "_gtensor.npy")
    
    # Read molecule
    mol = tq.Molecule(geometry_angstrom, n_pno="read", name=molecule_name, active_orbitals=active_orbitals) #Important here geometry in Angstrom
    
    #FCI
    c, h1, h2 = mol.get_integrals(ordering="chem")
    e, fcivec = pyscf.fci.direct_spin0.kernel(h1, h2.elems, mol.n_orbitals, mol.n_electrons)
    fci_energy = e + c
    print("FCI energy: " + (str)(fci_energy))
    iteration_energies.append(fci_energy.__str__())
    
    # Write 1rdm and 2rdm for iteration step
    rdm1, rdm2 = pyscf.fci.direct_spin0.make_rdm12(fcivec, mol.n_orbitals, mol.n_electrons)
    rdm2 = np.swapaxes(rdm2,1,2) # IMPORTANT: RE-SORTING FROM RDMS
    
    OrbOpt_helper.write_rdms(rdm1, rdm2, it_str + "/" + molecule_name)
    all_occ_number.append(np.sort(np.linalg.eig(rdm1)[0])[::-1])
    
    # Delete h and g tensors from the current folder and create folder for next iteration step
    os.remove(molecule_name + "_htensor.npy")
    os.remove(molecule_name + "_gtensor.npy")
    os.mkdir((it + 1).__str__())
    
    # Create OrbitalOptimization input file
    OrbOptFilePath = "madness_input.json"
    OrbOpt_helper.create_orbital_opt_input(OrbOptFilePath, it, all_orbitals, frozen_occupied_orbitals, active_orbitals, 
                                 box_size, wavelet_order, madness_thresh, optimization_thresh, NO_occupation_thresh,
                                 molecule_name)
    
    shutil.copy("madness_input.json", it_str + "/madness_input.json")
    
    # Execute orbital optimization
    programm = sp.call("/workspaces/MRA-OrbitalOptimization/build/OrbitalOptimization madness_input.json", stdout=open(it_str + '/log', 'w'), stderr=open(it_str + '/err_log', 'w'), shell = True)
    
    # The new h and g tensors from the orbital optimization must now be expanded to “number_total_orbs”, otherwise they cannot be read by tequila
    next_it_str = (it + 1).__str__()
    shutil.move(next_it_str + "/htensor.npy", next_it_str + "/htensor_limited.npy")
    shutil.move(next_it_str + "/gtensor.npy", next_it_str + "/gtensor_limited.npy")
    h_tensor_limited = np.load(next_it_str + "/htensor_limited.npy")
    g_tensor_limited = np.load(next_it_str + "/gtensor_limited.npy")
    h_tensor_full = np.zeros((number_total_orbs, number_total_orbs))
    g_tensor_full = np.zeros((number_total_orbs, number_total_orbs, number_total_orbs, number_total_orbs))
    for i in range(len(all_orbitals)):
        for j in range(len(all_orbitals)):
            orb1 = all_orbitals[i]
            orb2 = all_orbitals[j]
            h_tensor_full[orb1, orb2] = h_tensor_limited[i,j]
            for k in range(len(all_orbitals)):
                for l in range(len(all_orbitals)):
                    orb3 = all_orbitals[k]
                    orb4 = all_orbitals[l]
                    g_tensor_full[orb1, orb2, orb3, orb4] = g_tensor_limited[i,j,k,l]
    np.save(next_it_str + "/htensor.npy", h_tensor_full)
    np.save(next_it_str + "/gtensor.npy", g_tensor_full)


# Write energies to the hard disk
with open(r'Energies.txt', 'w') as fp:
    fp.write('\n'.join(iteration_energies))
    
# Write NO-Occupations to the hard disk
all_occ_number_matrix = np.column_stack(all_occ_number)
np.savetxt('all_occ_number.txt', all_occ_number_matrix)